(function(g){var window=this;'use strict';var c_=function(K){K.publish("cardstatechange",K.uW()&&K.LM()?1:0)},Ts=function(K,H){var r=g.Tm(H),O=r?H:arguments;
for(r=r?0:1;r<O.length;r++){if(K==null)return;K=K[O[r]]}return K},SOG=function(K){var H=g.my(K);
K=g.p3(K);return new g.L3(H.x,H.y,K.width,K.height)},VeQ=function(K,H,r){var O;
return O=g.Dh(K,H,function(){g.yW(O);r.apply(K,arguments)},{})},$i=function(K){K=g.P5(K);
delete QF[K];g.zL(QF)&&EN&&EN.stop()},lgL=function(){EN||(EN=new g.Ko(function(){te4()},20));
var K=EN;K.isActive()||K.start()},te4=function(){var K=g.St();
g.$G(QF,function(H){WTL(H,K)});
g.zL(QF)||lgL()},xi=function(K,H,r,O){g.ZB.call(this);
if(!Array.isArray(K)||!Array.isArray(H))throw Error("Start and end parameters must be arrays");if(K.length!=H.length)throw Error("Start and end points must be the same length");this.Y=K;this.G=H;this.duration=r;this.V=O;this.coords=[];this.progress=this.W=0;this.N=null},WTL=function(K,H){H<K.startTime&&(K.endTime=H+K.endTime-K.startTime,K.startTime=H);
K.progress=(H-K.startTime)/(K.endTime-K.startTime);K.progress>1&&(K.progress=1);K.W=1E3/(H-K.N);K.N=H;G_Y(K,K.progress);K.progress==1?(K.K=0,$i(K),K.onFinish(),K.r5()):K.isPlaying()&&K.pV()},G_Y=function(K,H){typeof K.V==="function"&&(H=K.V(H));
K.coords=Array(K.Y.length);for(let r=0;r<K.Y.length;r++)K.coords[r]=(K.G[r]-K.Y[r])*H+K.Y[r]},zgG=function(K,H){g.yG.call(this,K);
this.coords=H.coords;this.x=H.coords[0];this.y=H.coords[1];this.z=H.coords[2];this.duration=H.duration;this.progress=H.progress;this.fps=H.W;this.state=H.K},P_=function(K,H,r,O,A){xi.call(this,H,r,O,A);
this.element=K},g7=function(K,H,r,O,A){if(H.length!=2||r.length!=2)throw Error("Start and end points must be 2D");
P_.call(this,K,H,r,O,A)},CpK=function(K){return Math.pow(K,3)},J2Q=function(K){return 3*K*K-2*K*K*K},LT=function(K){return K.baseUrl||null},NJ=function(K,H){return g.aP(g.nO(K,H),r=>!!r)},sax=function(K,H,r){function O(xN){var m1=xN.hovercardButton;
if(!m1)return null;m1=m1.subscribeButtonRenderer;if(!m1)return null;var pO=k(m1.unsubscribedButtonText),kv=k(m1.subscribedButtonText);if(m1.subscribed){var N9=k(m1.subscriberCountWithUnsubscribeText);var C5=k(m1.subscriberCountText)}else N9=k(m1.subscriberCountText),C5=k(m1.subscriberCountWithSubscribeText);var ou=null;return xN.signinEndpoint&&((ou=Ts(xN,"signinEndpoint","webNavigationEndpointData","url"))||(ou=g.C(m1.signInEndpoint?.commandMetadata,g.Xs)?.url),!ou)?null:pO&&(kv||ou)?{subscribed:m1.subscribed,
subscribeText:pO,subscribeCount:N9,unsubscribeText:kv,unsubscribeCount:C5,enabled:m1.enabled,signinUrl:ou,classic:xN.useClassicSubscribeButton}:null}
function A(xN){if(xN){var m1=[],pO=xN.videoId;pO&&m1.push("v="+pO);(pO=xN.playlistId)&&m1.push("list="+pO);(xN=xN.startTimeSeconds)&&m1.push("t="+xN);return"/watch?"+m1.join("&")}}
function k(xN){if(!xN)return null;var m1=xN.simpleText;return m1?m1:xN.runs?g.nO(xN.runs,pO=>pO.text).join(""):null}
H=H.endscreenElementRenderer;if(!H)return null;var b=H.style,D=H.endpoint||{},y=null,B=null,Z=!1,F=null,X=null,w=null,T=null,S=!1,G=null,z=null,m=null,a=null,n=null,r4=null;if(b==="VIDEO")g.C(D,g.C$)?y=g.C(D,g.C$).url:(r4=g.C(D,g.QC),y=A(r4)),B=!1,F=K,H.thumbnailOverlays?(Z=H.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,X=k(Z.text),Z=Z.style==="LIVE"):X=k(H.videoDuration);else if(b==="PLAYLIST")g.C(D,g.C$)?y=g.C(D,g.C$).url:(r4=g.C(D,g.QC),y=A(r4)),B=!1,F=K,w=k(H.playlistLength);else if(b===
"CHANNEL"){if(S=Ts(D,"browseEndpoint","browseId"))T=S,y=`/channel/${T}`;B=!1;F="new";(S=!!H.isSubscribe)?G=O(H):z=k(H.subscribersText)}else b==="WEBSITE"?((m=Ts(D,"urlEndpoint","url"))&&(y=m),B=!0,F="new",m=H.icon.thumbnails[0].url):b==="CREATOR_MERCHANDISE"&&(H.productPrice&&(a=k(H.productPrice)),H.additionalFeesText&&(n=k(H.additionalFeesText)),(B=Ts(D,"urlEndpoint","url"))&&(y=B),B=!0,F="new");K=Ts(H,"title","accessibility","accessibilityData","label");var Xd=H.endpoint?H.endpoint.clickTrackingParams:
null,$N="";if(H.metadata){let xN=k(H.metadata);xN&&($N=xN)}return{id:`element-${r}`,type:b,title:k(H.title),metadata:$N,callToAction:k(H.callToAction),BS:H.image,iconUrl:m,left:Number(H.left),width:Number(H.width),top:Number(H.top),aspectRatio:Number(H.aspectRatio),startMs:Math.floor(Number(H.startMs)),endMs:Math.floor(Number(H.endMs)),videoDuration:X,Gk:Z,playlistLength:w,channelId:T,subscribeButton:G,subscribersText:z,isSubscribe:S,targetUrl:y||null,Ac:B,sessionData:Xd?{itct:Xd}:null,xq:F,yR:K?
K:null,isPlaceholder:H.isPlaceholder,impressionUrls:NJ(H.impressionUrls||[],LT),HR:NJ(H.hovercardShowUrls||[],LT),clickUrls:NJ(D.loggingUrls||[],LT),visualElement:g.QT(H.trackingParams),productPrice:a,additionalFeesText:n,watchEndpoint:r4||null}},Yi=function(K,H){var r={startMs:Math.floor(Number(K.startMs)),
impressionUrls:NJ(K.impressionUrls||[],LT),elements:NJ(K.elements||[],(O,A)=>sax(H,O,A))};
K.trackingParams&&(r.visualElement=g.QT(K.trackingParams));return r},UN=function(K){return K.player.X().playerStyle==="creator-endscreen-editor"},mbK=function(K){return K.player.getVideoData().NQ?"current":K.C?"new":"current"},S4=function(K,H,r=!0){K.player.sN("creatorendscreen");
K.B&&(K.B.dispose(),K.B=null,K.V.dispose(),K.V=null);for(var O of Object.values(K.Y))O.dispose();K.Y={};K.W={};K.j.length>0&&(K.j.forEach(A=>{A.dispose()}),K.j.length=0);
K.K&&(g.j5(K.K,"ytp-ce-element-show"),K.K.setAttribute("aria-hidden","true"));K.G=0;if((K.endscreen=H)&&H.elements){r&&agG(K);r=[];O=new g.bZ(H.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});r.push(O);K.player.X().B||(K.B=new g.R({L:"div",S:"ytp-ce-shadow"}),g.hC(K.player,K.B.element,4),K.V=new g.t$(K.B,200));for(O=0;O<H.elements.length;++O){let A=H.elements[O],k=fg4(K,A);if(!k){g.WZ(new g.Ln("buildEndscreenElement null",A));continue}K.Y[A.id]=k;K.W[A.id]=A;g.hC(K.player,
k.element,4);let b=new g.bZ(A.startMs,A.endMs,{id:"ytp-ce-element-"+A.id,namespace:"creatorendscreen"});r.push(b);nkY(K,k,A)}K.player.No(r);K.u1()}},hgS=function(K){var H=K.player.getVideoData(),r=H.videoId;
K.N&&K.N.abort();r={method:"POST",onFinish:A=>{var k=K.N=null;A.status===200&&(A=A.responseText,A.substring(0,3)===")]}"&&(A=A.substring(3),k=JSON.parse(A),k=Yi(k,mbK(K))));S4(K,k)},
urlParams:{v:r},withCredentials:!0};K.C&&(r.urlParams.ptype="embedded");var O=H.Da;O&&(r.postParams={ad_tracking:O});if(H=g.SgN(H))if(H=g.lO(H),H=g.UV(H))K.N=g.At(H,r)},agG=function(K){var H=g.xH(),r=g.PZ();
r&&H&&K.endscreen.visualElement&&g.iw(g.RZ)(void 0,r,H,K.endscreen.visualElement)},fg4=function(K,H){var r=null;
switch(H.type){case "VIDEO":K={L:"div",ob:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":H.yR||"","aria-hidden":"true"},J:[{L:"div",S:"ytp-ce-element-shadow"},{L:"div",S:"ytp-ce-covering-image",U:VF(H)},{L:"div",S:"ytp-ce-covering-shadow-top"},{L:"a",S:"ytp-ce-covering-overlay",U:{href:t6(K,H.targetUrl),tabindex:"-1"},J:[{L:"div",ob:["ytp-ce-video-title","ytp-webkit-ellipsis"],U:{dir:g.cp(H.title||"")},ek:H.title},{L:"div",S:H.Gk?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ek:H.videoDuration||void 0}]}]};r=new g.R(K);break;case "PLAYLIST":K={L:"div",ob:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":H.yR||"","aria-hidden":"true"},J:[{L:"div",S:"ytp-ce-element-shadow"},{L:"div",S:"ytp-ce-covering-image",U:VF(H)},{L:"div",S:"ytp-ce-covering-shadow-top"},{L:"a",S:"ytp-ce-covering-overlay",U:{href:t6(K,H.targetUrl),tabindex:"-1"},J:[{L:"div",ob:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],U:{dir:g.cp(H.title||"")},ek:H.title},{L:"div",S:"ytp-ce-playlist-count",
J:[{L:"div",S:"ytp-ce-playlist-icon"},{L:"div",S:"ytp-ce-playlist-count-text",ek:H.playlistLength||void 0}]}]}]};r=new g.R(K);break;case "CHANNEL":r={L:"div",ob:["ytp-ce-element","ytp-ce-channel",H.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":H.yR||"","aria-hidden":"true"},J:[{L:"div",S:"ytp-ce-element-shadow"},{L:"div",S:"ytp-ce-expanding-overlay",J:[{L:"div",S:"ytp-ce-expanding-overlay-hider"},{L:"div",S:"ytp-ce-expanding-overlay-background"},{L:"div",S:"ytp-ce-expanding-overlay-content",
J:[{L:"div",S:"ytp-ce-expanding-overlay-body",J:[{L:"div",S:"ytp-ce-expanding-overlay-body-padding",J:[{L:"a",ob:["ytp-ce-channel-title","ytp-ce-link"],U:{href:t6(K,H.targetUrl),target:"_blank",tabindex:"-1",dir:g.cp(H.title||"")},ek:H.title},H.subscribeButton?{L:"div",S:"ytp-ce-subscribe-container",J:[{L:"div",S:"ytp-ce-channel-subscribe"}]}:"",H.subscribersText?{L:"div",S:"ytp-ce-channel-subscribers-text",U:H.yR?{"aria-hidden":"true"}:{},ek:H.subscribersText}:"",H.metadata?{L:"div",ob:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],ek:H.metadata}:""]}]}]}]},{L:"div",S:"ytp-ce-expanding-image",U:VF(H)}]};r=new g.R(r);let A=g.aw(document,"div","ytp-ce-channel-subscribe",r.element)[0];if(H.subscribeButton&&H.channelId){g.DB(A,"ytp-ce-subscribe-button");let k;if(K.player.X().B){var O=null;k=H.sessionData.itct}else O="endscreen",k=null;O=new uvK(H.subscribeButton.subscribeText,H.subscribeButton.subscribeCount,H.subscribeButton.unsubscribeText,H.subscribeButton.unsubscribeCount,!!H.subscribeButton.enabled,
!!H.subscribeButton.classic,H.channelId,!!H.subscribeButton.subscribed,O,k,K.player);A.appendChild(O.element);K.j.push(O)}break;case "WEBSITE":K={L:"div",ob:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":H.yR||"","aria-hidden":"true"},J:[{L:"div",S:"ytp-ce-element-shadow"},{L:"div",S:"ytp-ce-expanding-overlay",J:[{L:"div",S:"ytp-ce-expanding-overlay-hider"},{L:"div",S:"ytp-ce-expanding-overlay-background"},{L:"div",S:"ytp-ce-expanding-overlay-content",J:[{L:"div",S:"ytp-ce-expanding-overlay-body",
J:[{L:"div",S:"ytp-ce-expanding-overlay-body-padding",J:[{L:"div",S:"ytp-ce-website-title",U:{dir:g.cp(H.title||"")},ek:H.title},{L:"div",S:"ytp-ce-website-metadata",ek:H.metadata},{L:"a",ob:["ytp-ce-website-goto","ytp-ce-link"],U:{href:t6(K,H.targetUrl),target:"_blank",tabindex:"-1"},ek:H.callToAction}]}]}]}]},{L:"div",S:"ytp-ce-expanding-image",U:VF(H)},{L:"div",S:"ytp-ce-expanding-icon",U:qO4(H.iconUrl)}]};r=new g.R(K);break;case "CREATOR_MERCHANDISE":r="",H.productPrice&&(r={L:"div",S:"ytp-ce-merchandise-price-container",
J:[{L:"div",S:"ytp-ce-merchandise-price",ek:H.productPrice}]},H.additionalFeesText&&r.J.push({L:"div",S:"ytp-ce-merchandise-additional-fees",ek:H.additionalFeesText})),K={L:"div",ob:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":H.yR||"","aria-hidden":"true"},J:[{L:"div",S:"ytp-ce-element-shadow"},{L:"div",S:"ytp-ce-expanding-overlay",J:[{L:"div",S:"ytp-ce-expanding-overlay-hider"},{L:"div",S:"ytp-ce-expanding-overlay-background"},{L:"div",S:"ytp-ce-expanding-overlay-content",
J:[{L:"div",S:"ytp-ce-expanding-overlay-body",J:[{L:"div",S:"ytp-ce-expanding-overlay-body-padding",J:[{L:"div",S:"ytp-ce-merchandise-title",U:{dir:g.cp(H.title||"")},ek:H.title},r,{L:"div",S:"ytp-ce-merchandise-metadata",ek:H.metadata},{L:"a",ob:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:t6(K,H.targetUrl),target:"_blank",tabindex:"-1"},ek:H.callToAction}]}]}]}]},{L:"div",S:"ytp-ce-expanding-image",U:VF(H)},{L:"div",S:"ytp-ce-merchandise-invideo-cta-container",J:[{L:"div",S:"ytp-ce-merchandise-invideo-cta",
ek:H.callToAction||void 0}]}]},r=new g.R(K)}H.isPlaceholder&&g.DB(r.element,"ytp-ce-placeholder");return r},nkY=function(K,H,r){function O(){b(1)}
function A(){b(-1)}
H.listen("mouseenter",()=>{lQ(K,H,r)});
H.listen("mouseleave",()=>{W_(K,H,r)});
K.player.X().B||H.listen("click",()=>{g.DB(H.element,"ytp-ce-element-hover")});
H.listen("click",D=>{p90(K,r,D)});
H.listen("keypress",D=>{p90(K,r,D)});
H.listen("focus",()=>{lQ(K,H,r)});
H.listen("blur",()=>{W_(K,H,r)});
H.listen("touchstart",()=>{lQ(K,H,r)});
var k=g.he("ytp-ce-expanding-overlay-hider",H.element);k&&H.Z(k,"touchstart",D=>{D.stopPropagation();g.j5(H.element,"ytp-ce-element-hover");g.j5(H.element,"ytp-ce-force-expand")});
H.listen("keydown",D=>{K.Ib=D.keyCode===9&&!D.shiftKey});
var b=D=>{K.G+=D;K.G>0?(g.DB(H.element,"ytp-ce-force-expand"),Gs(K,r.id,!0)):(g.j5(H.element,"ytp-ce-force-expand"),g.j5(H.element,"ytp-ce-element-hover"),Gs(K,r.id,!1))};
k=D=>{D&&(H.listen("blur",()=>{D.style.display!="none"&&K.Ib&&D.focus()}),H.Z(D,"focus",O),H.Z(D,"blur",A))};
k(g.he("ytp-sb-subscribe",H.element));k(g.he("ytp-sb-unsubscribe",H.element));H.listen("focus",O);H.listen("blur",A)},zs=function(K,H,r){function O(){k||(A++,A===H.length&&(b.stop(),r&&r()))}
if(!H||H.length===0||UN(K))r&&r();else{H=Rgo(K,H);var A=0,k=!1,b=new g.Ko(()=>{k=!0;r&&r()},1E3,K);
b.start();for(K=0;K<H.length;K++)g.uR(H[K],O)}},VF=function(K){if(K.BS)var H=K.BS.thumbnails;
return qO4(H?H[H.length-1].url:null)},t6=function(K,H){K=K.player.X();
if(H){if(H.startsWith("//"))return K.protocol+":"+H;if(H.startsWith("/"))return g.sX(K)+H}else return"";return H},qO4=function(K){return K?{style:"background-image: url("+K+")"}:{}},lQ=function(K,H,r){g.bd(H.element,"ytp-ce-element-hover")||(r.type==="VIDEO"||r.type==="PLAYLIST"?g.DB(H.element,"ytp-ce-element-hover"):K.player.X().B?(new g.Ko(()=>{g.DB(H.element,"ytp-ce-element-hover")},200)).start():g.DB(H.element,"ytp-ce-element-hover"),zs(K,r.HR),Gs(K,r.id,!0))},W_=function(K,H,r){g.j5(H.element,
"ytp-ce-element-hover");
g.j5(H.element,"ytp-ce-force-expand");Gs(K,r.id,!1)},p90=function(K,H,r){if(H.targetUrl&&(!r||r.type!=="keypress"||r.keyCode===13)){for(var O=r.target;O&&!g.bd(O,"ytp-ce-element");){g.bd(O,"subscribe-label")&&CT(K,H);
if(g.bd(O,"ytp-ce-channel-subscribe"))return;O=O.parentElement||null}if(!O||g.bd(O,"ytp-ce-element-hover")){r.preventDefault();r.stopPropagation();if(O=K.Y[H.id])W_(K,O,H),O.element.blur();if(r.ctrlKey||r.metaKey||H.xq==="new")CT(K,H),K.player.sendVideoStatsEngageEvent(17,void 0),K.player.pauseVideo(),r=g.lO(t6(K,H.targetUrl)),r=g.UV(r),g.yr(r,void 0,H.sessionData);else{let A=g.SR(K.player.X())||K.player.getVideoData().NQ,k=()=>{var b=t6(K,H.targetUrl),D=H.sessionData,y=H.watchEndpoint,B=g.zF(b);
A&&B&&(B.v||B.list)?K.player.v9(B.v,D,B.list,!1,void 0,y||void 0):g.DV(b,D)};
CT(K,H,()=>{K.player.sendVideoStatsEngageEvent(17,k)})}}}},Gs=function(K,H,r){K.B&&(r?K.V.show():K.V.hide());
for(let O of Object.keys(K.Y))O!==H&&g.Bp(K.Y[O].element,"ytp-ce-element-shadow-show",r)},CT=function(K,H,r){zs(K,H.clickUrls,r);
(K=g.PZ())&&H.Ac&&g.ME(K,H.visualElement)},Rgo=function(K,H){var r=K.player.getVideoData().clientPlaybackNonce;
K=K.player.getCurrentTime().toFixed(2);r={CPN:r,AD_CPN:r,MT:K};K=[];for(let O=0;O<H.length;O++)K.push(iR4(H[O],r));return K},iR4=function(K,H){return K.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,r=>{var O=unescape(r);
O=O.substring(1,O.length-1);return H[O]?escape(H[O]):r})},KqY=function(K){return typeof K==="string"?K:""},J6=function(K,H,r){for(let O in H)if(H[O]===K)return K;
return r},sN=function(K){if(!K)return null;
var H=g.lO(KqY(K.value));H=g.UV(H);if(!H)return null;var r=J6(K.target,Hzx,"current");if(r==null)K=null;else{var O=K.show_link_icon;K=new rOL(H,r,O==="true"||O==="false"?O==="true":!0,K.pause_on_navigation!=null?K.pause_on_navigation:!0)}return K},bz5=function(K){if(!K)return null;
var H=J6(K.type,Ozx),r=J6(K.trigger,AOK);K=K.url;K=Array.isArray(K)&&K.length?K[0]:K;K=sN(K?K:null);return H?new k84(H,r,K):null},Dh0=function(K,H){return g.iJ(K.action,H)},mJ=function(K,H){K="background-image: url("+K+");";
var r=[];H&&r.push(H);return{L:"div",S:"iv-card-image",U:{style:K},J:r}},fT=function(K){return K.customMessage?ab("div","iv-card-message",K.customMessage):""},nT=function(K){if(!K.metaInfo||K.metaInfo.length===0)return"";
var H=[];for(let r of K.metaInfo)H.push(ab("li","",r));return{L:"ul",S:"iv-card-meta-info",J:H}},h6=function(K,H,r,O){if(O)for(let A of H)K.K(A,O,r.id,r.sessionData,r.Q0.click,5)},ab=function(K,H,r){H?typeof H==="string"?H={"class":H}:Array.isArray(H)&&(H={"class":H.join(" ")}):H={};
H.dir=g.cp(r);return{L:K,U:H,ek:r}},yO4=function(K){if(!K.customMessage)return"";
var H=["iv-card-action","iv-card-primary-link"],r={};K.c7&&(H.push("iv-card-action-icon"),r.style="background-image: url("+K.c7+");");r.dir=g.cp(K.customMessage);var O=[{L:"span",ek:K.customMessage}];K.showLinkIcon&&(O.push("\u00a0"),O.push({L:"span",S:"iv-card-link-icon"}));return{L:"div",ob:H,U:r,J:O}},jl5=function(K){var H;
(H=K)&&!(H=K.length>1?K.charAt(0)==="/"&&K.charAt(1)!=="/":K==="/")&&(H=K.replace(/^(https?:)?\/\//,"").split("/",1),H=!H||H.length<1||!H[0]?[]:H[0].toLowerCase().split(".").reverse(),H=H[0]==="com"&&H[1]==="youtube"||H[0]==="be"&&H[1]==="youtu");return H?K.indexOf("/redirect?")===-1:!1},Mmq=function(K,H){return H?H:jl5(K)?"current":"new"},uQ=function(K,H,r,O,A,k,b){K.context.K.listen(H,"click",D=>{K.jk(r,O,A,k||[],b||0,D)});
K.context.K.listen(H,"touchstart",()=>{K.fK=!1});
K.context.K.listen(H,"touchmove",()=>{K.fK=!0})},BqY=function(K){if(g.C(K,g.C$)?.url)return g.C(K,g.C$).url;
if((K=g.C(K,g.QC))&&K.videoId){let H="/watch?v="+K.videoId;K.playlistId&&(H+="&list="+K.playlistId);K.index&&(H+="&index="+K.index);K.startTimeSeconds&&(H+="&t="+K.startTimeSeconds);return H}return null},qJ=function(K,H,r){return{w8:(K.impressionLoggingUrlsV2s||[]).map(O=>O.baseUrl||""),
click:(r.loggingUrls||[]).map(O=>O.baseUrl||""),
close:(H.dismissLoggingUrlsV2s||[]).map(O=>O.baseUrl||""),
mL:(H.impressionLoggingUrlsV2s||[]).map(O=>O.baseUrl||""),
LV:(H.clickLoggingUrlsV2s||[]).map(O=>O.baseUrl||"")}},KK=function(K,H){if(H.onClickCommand&&g.C(H.onClickCommand,g.ZOu)?.targetId==="engagement-panel-error-corrections"){K.KK=H;
var r=!0}else r=!1;if(!r||vLS(K,H))if(r=IaG(K,H)){var O={JW:H,vH:r.element,B6:!1};if(H.onClickCommand)K.V6||Zz4(K),pT(K,H.id),r=K.findLastIndex(O),g.Iq(K.cards,r,0,O);else{K.isInitialized||FqK(K);pT(K,H.id);let A=K.findLastIndex(O);g.Iq(K.cards,A,0,O);r.Hn(K.Y,A);K.iG()}H.autoOpen?K.addCueRange(H.startMs,0x8000000000000,H.id,()=>{K.B||(K.K=O,Rb(K),elB(K,O),iQ(K,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(r=K.context.D.getCurrentTime()*1E3,r<5E3&&r>H.startMs&&oLq(K,O),K.addCueRange(H.startMs,H.startMs+1,H.id,
()=>{oLq(K,O)}),Rb(K))}},HJ=function(K){K.B&&(K.Ay.hide(),K.O5.Y(),g.j5(K.context.D.getRootNode(),g.km.IV_DRAWER_OPEN),K.B=!1,c_(K.D),K.V&&K.V.stop(),K.V=new g.Ko(()=>{K.wZ&&(K.wZ.focus(),K.wZ=null)},330),K.V.start())},Xyo=function(K,H){H=H.data;
H.autoOpenMs&&K.addCueRange(H.autoOpenMs,0x8000000000000,"",()=>{iQ(K,"YOUTUBE_DRAWER_AUTO_OPEN")});
H.autoCloseMs&&K.addCueRange(H.autoCloseMs,0x8000000000000,"",()=>{HJ(K)});
var r=H.headerText;g.vQ(K.aE,r);K.j&&K.j.setAttribute("data-tooltip-title",r);H.eventId&&(K.eventId=H.eventId);K.TF=g.QT(H.trackingParams);K.G=g.QT(H.closeTrackingParams);K.Vb=g.QT(H.iconTrackingParams)},ry=function(K,H,r){var O=-1,A=-1;
for(let k=0;k<K.length;k++){if(K[k].height===H||K[k].width===r)return K[k];((K[k].height||0)<H||(K[k].width||0)<r)&&(O<0||(K[O].height||0)<(K[k].height||0)||(K[O].width||0)<(K[k].width||0))?O=k:((K[k].height||0)>=H||(K[k].width||0)>=r)&&(A<0||(K[A].height||0)>(K[k].height||0)||(K[A].width||0)>(K[k].width||0))&&(A=k)}return K[A>=0?A:O]},Os=function(K,H,r,O){return{feature:r.feature?r.feature:"cards",
src_vid:K.context.videoData.videoId,annotation_id:H,ei:K.context.videoData.eventId||"",itct:O.trackingParams||""}},wyL=function(K,H){var r=H.cardId?H.cardId:`cr:${K.W}`,O=K.D.X().experiments.cn("enable_error_corrections_infocard_web_client");
if(!H.content&&H.teaser.simpleCardTeaserRenderer&&O){O=H.teaser.simpleCardTeaserRenderer;var A=H.icon?H.icon.infoCardIconRenderer:null;if(O.channelAvatar&&O.channelAvatar.thumbnails&&O.channelAvatar.thumbnails.length>0)var k=ry(O.channelAvatar.thumbnails,22,22).url;H={id:r,timestamp:K.W,type:"simple",teaserText:g.Xn(O.message),teaserDurationMs:Number(H.cueRanges[0].teaserDurationMs),startMs:Number(H.cueRanges[0].startCardActiveMs),autoOpen:!!H.autoOpen,sessionData:{},sponsored:!1,Q0:{},W$:null,d3:O.trackingParams?
g.QT(O.trackingParams):null,Vb:A&&A.trackingParams?g.QT(A.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,c7:null,title:"",customMessage:"",url:null,onClickCommand:O.onTapCommand||null,tv:k};KK(K,H)}else if(H.content?.simpleCardContentRenderer){if(!H.cueRanges.length)return;k=H.content?.simpleCardContentRenderer;O=H.teaser.simpleCardTeaserRenderer;A=H.icon?H.icon.infoCardIconRenderer:null;H={id:r,timestamp:K.W,type:"simple",teaserText:g.Xn(O.message),teaserDurationMs:Number(H.cueRanges[0].teaserDurationMs),
startMs:Number(H.cueRanges[0].startCardActiveMs),autoOpen:!!H.autoOpen,sessionData:Os(K,r,H,k),sponsored:!1,Q0:qJ(k,O,k.command),W$:k.trackingParams?g.QT(k.trackingParams):null,d3:O.trackingParams?g.QT(O.trackingParams):null,Vb:A&&A.trackingParams?g.QT(A.trackingParams):null,imageUrl:ry(k.image.thumbnails,290,290).url,displayDomain:k.displayDomain?g.Xn(k.displayDomain):null,showLinkIcon:!!k.showLinkIcon,c7:null,title:k.title?g.Xn(k.title):"",customMessage:k.callToAction?g.Xn(k.callToAction):"",url:g.C(k.command,
g.C$).url?sN({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:g.C(k.command,g.C$).url}):null,onClickCommand:null};KK(K,H)}else if(H.content?.collaboratorInfoCardContentRenderer){if(!H.cueRanges.length)return;k=H.content?.collaboratorInfoCardContentRenderer;O=H.teaser.simpleCardTeaserRenderer;A=H.icon?H.icon.infoCardIconRenderer:null;H={id:r,timestamp:K.W,type:"collaborator",teaserText:g.Xn(O.message),teaserDurationMs:Number(H.cueRanges[0].teaserDurationMs),startMs:Number(H.cueRanges[0].startCardActiveMs),
autoOpen:!!H.autoOpen,sessionData:Os(K,r,H,k),sponsored:!1,Q0:qJ(k,O,k.endpoint),W$:k.trackingParams?g.QT(k.trackingParams):null,d3:O.trackingParams?g.QT(O.trackingParams):null,Vb:A&&A.trackingParams?g.QT(A.trackingParams):null,channelId:g.C(k.endpoint,g.vO).browseId,customMessage:k.customText?g.Xn(k.customText):null,profileImageUrl:ry(k.channelAvatar.thumbnails,290,290).url,title:k.channelName?g.Xn(k.channelName):"",metaInfo:[k.subscriberCountText?g.Xn(k.subscriberCountText):""],url:sN({pause_on_navigation:!K.context.videoData.isLivePlayback,
target:"new",value:g.C(k.endpoint,g.vO).canonicalBaseUrl?g.C(k.endpoint,g.vO).canonicalBaseUrl:`/channel/${g.C(k.endpoint,g.vO).browseId}`}),onClickCommand:null};KK(K,H)}else if(H.content?.playlistInfoCardContentRenderer){if(!H.cueRanges.length)return;k=H.content?.playlistInfoCardContentRenderer;O=H.teaser.simpleCardTeaserRenderer;A=H.icon?H.icon.infoCardIconRenderer:null;H={id:r,timestamp:K.W,type:"playlist",teaserText:g.Xn(O.message),teaserDurationMs:Number(H.cueRanges[0].teaserDurationMs),startMs:Number(H.cueRanges[0].startCardActiveMs),
autoOpen:!!H.autoOpen,sessionData:Os(K,r,H,k),sponsored:!1,Q0:qJ(k,O,k.action),W$:k.trackingParams?g.QT(k.trackingParams):null,d3:O.trackingParams?g.QT(O.trackingParams):null,Vb:A&&A.trackingParams?g.QT(A.trackingParams):null,Iz:ry(k.playlistThumbnail.thumbnails,258,290).url,customMessage:k.customMessage?g.Xn(k.customMessage):null,playlistVideoCount:g.Xn(k.playlistVideoCount),title:k.playlistTitle?g.Xn(k.playlistTitle):"",metaInfo:[k.channelName?g.Xn(k.channelName):"",k.videoCountText?g.Xn(k.videoCountText):
""],url:sN({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:BqY(k.action)}),onClickCommand:null};KK(K,H)}else if(H.content?.videoInfoCardContentRenderer){if(!H.cueRanges.length)return;k=H.content?.videoInfoCardContentRenderer;O=H.teaser.simpleCardTeaserRenderer;A=H.icon?H.icon.infoCardIconRenderer:null;H={id:r,timestamp:K.W,type:"video",teaserText:g.Xn(O.message),teaserDurationMs:Number(H.cueRanges[0].teaserDurationMs),startMs:Number(H.cueRanges[0].startCardActiveMs),autoOpen:!!H.autoOpen,
sessionData:Os(K,r,H,k),sponsored:!1,Q0:qJ(k,O,k.action),W$:k.trackingParams?g.QT(k.trackingParams):null,d3:O.trackingParams?g.QT(O.trackingParams):null,Vb:A&&A.trackingParams?g.QT(A.trackingParams):null,Iz:ry(k.videoThumbnail.thumbnails,258,290).url,videoDuration:k.lengthString?g.Xn(k.lengthString):null,customMessage:k.customMessage?g.Xn(k.customMessage):null,title:k.videoTitle?g.Xn(k.videoTitle):"",metaInfo:[k.channelName?g.Xn(k.channelName):"",k.viewCountText?g.Xn(k.viewCountText):""],isLiveNow:!!k.badge,
url:sN({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:BqY(k.action)}),onClickCommand:null};KK(K,H)}K.W++},dh4=function(K,H){return g.iJ(K.cards,r=>r.JW.id===H)},Rb=function(K){g.Bp(K.D.getRootNode(),"ytp-cards-shopping-active",cOQ(K))},pT=function(K,H){if(H=dh4(K,H))H===K.K&&(K.K=null),K.D.removeCueRange(H.JW.id),g.Mu(H.vH),g.b0(K.cards,H),K.iG(),Rb(K)},iQ=function(K,H,r){if(!K.B){K.Ay.show();
K.hy=new g.Ko(()=>{g.DB(K.context.D.getRootNode(),g.km.IV_DRAWER_OPEN)},0);
K.hy.start();K.O5.Z(K.Y,"mousewheel",A=>{K.zF.start();A.preventDefault();A=A||window.event;var k=0;A.type=="MozMousePixelScroll"?k=0==(A.axis==A.HORIZONTAL_AXIS)?A.detail:0:window.opera?k=A.detail:k=A.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?A.wheelDeltaY/-30:A.wheelDeltaY/-1.2:A.wheelDelta/-1.6:A.wheelDeltaY/-3;if(A=k)K.Y.scrollTop+=A});
K.B=!0;var O=g.PZ();O&&K.TF&&K.G&&g.yU(O,[K.TF,K.G]);H={TRIGGER_TYPE:H};for(let A of K.cards)A.B6||(A.B6=!0,Tq4(K.context.logger,A.JW.Q0.w8,H)),O&&g.yU(O,[A.JW.W$]);c_(K.D);r&&(K.V=new g.Ko(()=>{K.wZ=K.j;K.vn.focus()},330),K.V.start())}},FqK=function(K){g.y0(K.zL(),[g.km.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.hC(K.D,K.N,5);K.GP();K.j=g.he("ytp-cards-button",K.D.getRootNode());K.vn=g.he("iv-drawer-close-button",K.N);K.isInitialized=!0},Zz4=function(K){K.Ib.push(g.jP("iv-teaser-shown",K.XH,K));
K.Ib.push(g.jP("iv-teaser-hidden",K.E1,K));K.Ib.push(g.jP("iv-teaser-clicked",K.Pl,K));K.V6=!0},vLS=function(K,H){K.KK=H;
var r=K.D.getVideoData();if(!r)return!1;r=g.DR(r.getWatchNextResponse());if(r?.markersMap)for(let A=0;r?.markersMap.length>A;A++){var O=r?.markersMap[A];if(O.key==="ERROR_CORRECTION_MARKERS"&&(O=O.value?.markers)&&O.length>0)return H.startMs=g.C(O[0],g.UP5)?.timeRangeStartMillis||0,K.KK=null,!0}return!1},IaG=function(K,H){switch(H.type){case "simple":K=K.Nd;
var r=H.displayDomain?{L:"div",S:"iv-card-image-text",ek:H.displayDomain}:void 0;var O=yO4(H);r={L:"div",ob:["iv-card"],J:[{L:"a",S:"iv-click-target",U:{href:H.url?H.url.K()||"":""},J:[mJ(H.imageUrl,r),{L:"div",S:"iv-card-content",J:[ab("h2",void 0,H.title),O]}]}]};r=new g.R(r);h6(K,g.m3("iv-click-target",r.element),H,H.url);H=r;break;case "collaborator":K=K.Nd;r={L:"div",ob:["iv-card","iv-card-channel"],J:[{L:"a",ob:["iv-click-target"],U:{href:H.url.K()||"","data-ytid":H.channelId},J:[mJ(H.profileImageUrl),
{L:"div",S:"iv-card-content",J:[fT(H),{L:"h2",S:"iv-card-primary-link",ek:H.title},nT(H)]}]}]};r=new g.R(r);h6(K,g.m3("iv-click-target",r.element),H,H.url);H=r;break;case "playlist":K=K.Nd;r={L:"div",ob:["iv-card","iv-card-playlist"],J:[{L:"a",S:"iv-click-target",U:{href:H.url.K()||""},J:[mJ(H.Iz,{L:"div",S:"iv-card-image-overlay",J:[{L:"span",S:"iv-card-playlist-video-count",ek:H.playlistVideoCount}]}),{L:"div",S:"iv-card-content",J:[fT(H),ab("h2","iv-card-primary-link",H.title),nT(H)]}]}]};r=new g.R(r);
h6(K,g.m3("iv-click-target",r.element),H,H.url);H=r;break;case "productListing":K=K.Nd;var A=H.offers.length!=0;r=["iv-card"];O="";var k=yO4(H);A&&(r.push("iv-card-product-listing"),O="iv-card-primary-link",k=H.offers[0],A=[],k.price&&A.push({L:"div",S:"iv-card-offer-price",ek:k.price}),k.merchant&&A.push({L:"div",S:"iv-card-offer-merchant",ek:k.merchant}),k={L:"div",J:A});A=H.url?H.url.K()||"":"";r={L:"div",ob:r,U:{tabindex:"0"},J:[{L:"a",ob:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
H.imageUrl+");",href:A,"aria-hidden":"true",tabindex:"-1"}},{L:"div",S:"iv-card-content",J:[H.sponsored?{L:"div",S:"iv-card-sponsored",J:["Sponsored",{L:"div",S:"iv-ad-info-container",J:[{L:"div",S:"iv-ad-info",ek:"{{adInfo}}"},{L:"div",S:"iv-ad-info-icon-container",J:[{L:"div",S:"iv-ad-info-icon"},{L:"div",S:"iv-ad-info-callout"}]}]}]}:"",{L:"a",S:"iv-click-target",U:{href:A},J:[ab("h2",O,H.title),k]}]}]};r=new g.R(r);O=g.ka("span");g.vQ(O,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
r.setContent(O,"adInfo");h6(K,g.m3("iv-click-target",r.element),H,H.url);H=r;break;case "video":K=K.Nd;r=H.isLiveNow?{L:"span",ob:["yt-badge","yt-badge-live"],ek:"LIVE NOW"}:null;r={L:"div",ob:["iv-card","iv-card-video"],J:[{L:"a",S:"iv-click-target",U:{href:H.url?.K()||""},J:[mJ(H.Iz,H.videoDuration?{L:"span",S:"iv-card-video-duration",ek:H.videoDuration}:void 0),{L:"div",S:"iv-card-content",J:[fT(H),ab("h2","iv-card-primary-link",H.title),nT(H),r]}]}]};r=new g.R(r);h6(K,g.m3("iv-click-target",r.element),
H,H.url);H=r;break;default:return null}return H},oLq=function(K,H){if(!g.bd(K.D.getRootNode(),"ytp-cards-teaser-shown")){if(K.K!==H){var r=g.PZ(),O=K.K?K.K.JW.Vb:K.Vb;
r&&O&&g.jM(r,[O]);K.K=H;Rb(K)}(r=K.isInitialized&&K.zL().style.display=="none")||(r=K.context.D.getPlayerState(),O=r===0&&K.context.D.getCurrentTime()===0,r=!(r===1||r===3||O));r||H.JW.teaserDurationMs&&K.D.mG(!0,{teaserText:H.JW.teaserText,durationMs:H.JW.teaserDurationMs,onClickCommand:H.JW.onClickCommand,tv:H.JW.tv??null});K.pK.isActive()||((!K.B||!K.zF.isActive()&&K.Pn)&&elB(K,H),K.pK.start(910+H.JW.teaserDurationMs))}},cOQ=function(K){return K.K?K.K.JW.type==="productListing":K.D.O("enable_wn_infocards")?
!!K.cards?.length&&g.q9(K.cards,H=>H.JW.type==="productListing"):g.q9(K.cards,H=>H.JW.type==="productListing")},elB=function(K,H){K.C.TL?(H=new xi([0,
K.Y.scrollTop],[0,H.vH.offsetTop],600,J2Q),K.context.B.listen(H,"animate",r=>{K.Y.scrollTop=r.y}),K.context.B.listen(H,"finish",r=>{K.Y.scrollTop=r.y}),H.play()):(K.C.Au(!0),K.Y.scrollTop=H.vH.offsetTop,K.C.Au(!1))},AX=function(K){return K.K&&K.K.JW?K.K.JW:K.cards[0]&&K.cards[0].JW?K.cards[0].JW:null},QlQ=function(K){var H=K.annotation.data;
"start_ms"in H&&"end_ms"in H&&K.addCueRange(Number(H.start_ms),Number(H.end_ms),K.annotation.id,()=>{K.show()},()=>{K.hide()})},ELL=function(K,H){var r=SOG(H).width;
g.C3(H,r);r=new g7(H,[r,H.offsetTop],[r-r,H.offsetTop],200,CpK);g.W(K,r);K.context.B.listen(r,"begin",()=>{g.Rj(H,!0)});
r.play()},kZ=function(K,H,r){r.stopPropagation();
$hL(K);xhL(K,H);K.K.focus()},bk=function(K){K.N&&(g.Fd.clearTimeout(K.N),K.N=null)},$hL=function(K){K.V.stop();
K.isCollapsed&&(g.Mq(K.zL(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),K.isCollapsed=!1,K.K&&K.K.removeAttribute("aria-hidden"),g.Rj(K.Y,!1),g.Rj(K.B,!0))},xhL=function(K,H){K.N||(K.N=g.Cz(function(){bk(this);
Piu(this)},H,K))},Piu=function(K){K.isCollapsed||K.j||K.N||(g.DB(K.zL(),"iv-promo-collapsed"),K.isCollapsed=!0,K.V.start())},Tq4=function(K,H,r){H&&(r?Ds(K,H.map(O=>g.C7(O,r))):Ds(K,H))},Ds=function(K,H,r,O){var A=1,k=void 0,b=-1;
if(r){let D=!1;k=()=>{A--;A||D||(clearTimeout(b),D=!0,r())};
b=setTimeout(()=>{D=!0;r()},1E3)}for(let D of H||[])A++,g.uR(D,k);
O&&(A++,O!==0&&K.D.sendVideoStatsEngageEvent(O,k))},gL4=function(K){return K==="annotation-editor"||K==="live-dashboard"},Lqq=function(K){K.N&&(K.player.removeEventListener("videodatachange",K.N),K.N=null)},Nqq=function(K){K=K.createElement({L:"div",
ob:["annotation","annotation-type-custom"]});g.Rj(K,!1);return K},jQ=function(K,H){var r=!1,O=H.getElementsByTagName("annotations");
if(O&&!(O.length<1)&&(O=O[0].getAttribute("itct"))){var A=g.PZ();if(A){var k=g.xH();k&&g.iw(g.p1)(void 0,A,k,[g.QT(O)])}}H=H.getElementsByTagName("annotation");for(O=0;O<H.length;O++){var b=YD4(K,H[O]);A=null;try{a:{if(!b){A=null;break a}var D=b.id;k=/.+/;let w=typeof D==="string"&&k!=null&&D!=null&&D.match(k)?D:"",T=J6(b.type,UhB),S=J6(b.style,SDS),G=KqY(b.data),z=G.length!==0?JSON.parse(G):{};b:{var y=b.action;k=bz5;if(y==null){var B=null;break b}if(g.Tm(y)){b=[];for(let a of y){let n=k(a);n&&b.push(n)}B=
b;break b}let m=k(y);B=m?[m]:[]}k=B;A=w&&T?new Vm5(w,T,S,k,z):null}}catch(w){}if(A)if(A.type==="branding"||A.type==="promotion"){k=K;b=A;var Z=Nqq(k),F=null;switch(b.type){case "branding":var X=k.player.X();if(X.KB)break;X.Sk().K.s5(g.AE9)&&(F=b.nB(),F?.value&&(X=g.EL(F.value),!X.K&&X.Y.startsWith("/")&&(g.o4(X,"www.youtube.com"),g.eZ(X,"https"),F.value=X.toString())));k.player.O("web_player_overlay_positioned_layout")?(Z.setAttribute("data-overlay-order","11"),k.player.Y7(Z,4,!0)):k.Y.element.appendChild(Z);
F=new tmK(Z,yp(k),b);break;case "promotion":g.hC(k.player,Z,4),F=new laS(Z,yp(k),b)}F&&F.Bn();if(k=F)g.W(K,k),K.W[A.id]=k}else if(A.type==="card"||A.type==="drawer"){K.K||(K.K=Wq0(K),g.W(K,K.K));if(A.type==="card"){if(Z=K.K,X=(r=A)&&r.data&&r.data.card_type,A=r.data,X)switch(k=A.tracking||{},k={w8:k.impression,click:k.click,close:k.close,mL:k.teaser_impression,LV:k.teaser_click},b=A.tracking_params||{},F=null,X){case "collaborator":r={id:r.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,
teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Q0:k,W$:b.card?g.QT(b.card):null,d3:b.teaser?g.QT(b.teaser):null,Vb:b.icon?g.QT(b.icon):null,channelId:A.channel_id,customMessage:A.custom_message?A.custom_message:null,profileImageUrl:A.image_url,title:A.title,metaInfo:A.meta_info,url:sN({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};KK(Z,r);break;case "playlist":r=
{id:r.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Q0:k,W$:b.card?g.QT(b.card):null,d3:b.teaser?g.QT(b.teaser):null,Vb:b.icon?g.QT(b.icon):null,Iz:A.image_url,playlistVideoCount:A.playlist_video_count,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,url:sN({pause_on_navigation:A.pause_on_navigation,
target:A.target||"new",value:A.url}),onClickCommand:null};KK(Z,r);break;case "productListing":A.signin_url&&(F=sN({target:"current",value:A.signin_url}));X=[];let w=A.offers||[];for(let T=0;T<w.length;T++)X.push(new G8L(g.yo(w[T].merchant),g.yo(w[T].price)));r={id:r.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Q0:k,W$:b.card?g.QT(b.card):
null,d3:b.teaser?g.QT(b.teaser):null,Vb:b.icon?g.QT(b.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,c7:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?A.custom_message:null,url:sN({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),Mfd:F,iZG:A.signin_title?A.signin_title:void 0,T3K:A.signin_message?A.signin_message:void 0,offers:X,onClickCommand:null};KK(Z,r);break;
case "simple":r={id:r.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Q0:k,W$:b.card?g.QT(b.card):null,d3:b.teaser?g.QT(b.teaser):null,Vb:b.icon?g.QT(b.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,c7:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?
A.custom_message:null,url:sN({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};KK(Z,r);break;case "video":r={id:r.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Q0:k,W$:b.card?g.QT(b.card):null,d3:b.teaser?g.QT(b.teaser):null,Vb:b.icon?g.QT(b.icon):null,Iz:A.image_url,videoDuration:A.video_duration||
null,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,isLiveNow:!!A.is_live_now,url:sN({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null},KK(Z,r)}}else Xyo(K.K,A);r=!0}}r&&(c_(K.player),K.C())},zlY=function(K){var H=K.player.X();
K=K.player.getVideoData();return(H.annotationsLoadPolicy||K.annotationsLoadPolicy)===1&&!K.nR||H.O5.get(K.videoId)||g.yv(K)||g.jX(K)?!0:!1},CiL=function(K,H){H=!H.isCued()&&!H.K(1024);
K.Y.Au(H);K.B.Au(H)},aa0=function(K,H){var r=H.videoId,O=k=>{var b=K.loadNumber;
K.G=null;K.loaded&&K.loadNumber===b&&K.player.getVideoData().videoId===r&&(k=g.ng(k)&&k.responseXML?k.responseXML:null)&&(jQ(K,k),g.DB(K.player.getRootNode(),"iv-module-loaded"))};
g.VW()&&(O=JOQ(K,O));var A={format:"XML",onFinish:O,onError:()=>{K.G=null},
urlParams:{}};H.isPharma&&(A.urlParams.pharma="1");A.method="POST";A.withCredentials=!0;(O=K.player.X().O5.get(r))&&slG(A,O);O=O&&O.U3;if(!H.zx||O)K.N=()=>{if(!K.KK)K.onVideoDataChange(A);var k=K.player.getVideoData();g.De(k)&&!K.Ib&&mhQ(K,k)},K.player.addEventListener("videodatachange",K.N)},MO=function(K,H){var r=!1;
K.K||(K.K=Wq0(K),g.W(K,K.K));for(var O of H.cards||[])O.cardRenderer&&(wyL(K.K,O.cardRenderer),r=!0);r&&(g.De(K.player.getVideoData())||(r=K.K,O=H.headerText?g.Xn(H.headerText):"",g.vQ(r.aE,O),r.j&&r.j.setAttribute("data-tooltip-title",O),r.context.videoData.eventId&&(r.eventId=r.context.videoData.eventId),r.TF=H.trackingParams?g.QT(H.trackingParams):null,r.G=H.closeButton.infoCardIconRenderer.trackingParams?g.QT(H.closeButton.infoCardIconRenderer.trackingParams):null,r.Vb=H.icon.infoCardIconRenderer.trackingParams?
g.QT(H.icon.infoCardIconRenderer.trackingParams):null,K.C()),c_(K.player))},mhQ=function(K,H){if(H=H.getWatchNextResponse()?.cards?.cardCollectionRenderer)K.Ib=!0,MO(K,H),H.headerText&&K.hI&&(H=g.Xn(H.headerText),K.hI.setAttribute("data-tooltip-title",H))},JOQ=function(K,H){return(...r)=>{K.Md()||K.Bn.push(g.sL.sX(()=>{H(...r)}))}},slG=function(K,H){K.method="POST";
K.postParams=K.postParams||{};H.U3&&(K.postParams.ic_coll=H.U3);H.j4&&(K.postParams.ic_track=H.j4)},YD4=function(K,H){var r={};
for(var O of H.attributes)r[O.name]=O.nodeValue;for(O=0;O<H.childNodes.length;O++){let k=H.childNodes[O];if(!g.Qn(k)||k.nodeType!=1)continue;var A=void 0;if(r[k.tagName])A=r[k.tagName];else if(k.tagName==="data"){k.childNodes.length>0&&(A=k.childNodes[0].nodeValue,r[k.tagName]=typeof A==="string"?A.trim():A);continue}else A=[],r[k.tagName]=A;k&&k.tagName==="TEXT"?k.childNodes.length===1&&k.childNodes[0].nodeType===3?A.push(k.childNodes[0].nodeValue):A.push(""):k&&A.push(YD4(K,k))}return r},yp=function(K){if(!K.j){let H=
new fax(K);
g.W(K,H);let r=new g.gX(K);g.W(K,r);K.j=new nLx(H,r,K.player.X(),K.player.getVideoData(),K.logger,K.player,K.pE)}return K.j},hlx=function(K){var H=K.player.getVideoData();
if(H.SX){var r=K.player.X().O5.get(H.videoId);if(r){var O={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(A,k,b)=>{A=K.loadNumber;k=H.videoId;K.loaded&&K.loadNumber===A&&K.player.getVideoData().videoId===k&&(b=g.ng(b)&&b.responseXML?b.responseXML:null)&&jQ(K,b)}};
g.VW()&&(O.onFinish=JOQ(K,O.onFinish));O.postParams={ic_only:"1"};slG(O,r);K.KK=!0;g.At(H.SX,O)}}},Wq0=function(K){var H=new g.R({L:"div"});
g.Rj(H.element,!1);var r=new uxq(K.player,H.element,yp(K));g.W(r,H);H.Hn(K.Y.element);r.Bn();return r},qDS=function(K,H,r,O,A){if(!K.player.X().KB){var k=[];
H.navigationEndpoint&&g.C(H.navigationEndpoint,g.vO)&&g.C(H.navigationEndpoint,g.vO).browseId&&k.push(new k84("openUrl","click",new rOL(`/channel/${g.C(H.navigationEndpoint,g.vO).browseId}`,"new",!0,!0)));var b=H.watermark.thumbnails[0];O={channel_name:H.channelName,end_ms:H.endTimeMs,image_height:b.height,image_type:1,image_url:b.url,image_width:b.width,is_mobile:!1,session_data:{annotation_id:r,ei:A,feature:"iv",itct:H.trackingParams,src_vid:O},start_ms:H.startTimeMs};if(H.subscribeButton&&g.C(H.subscribeButton,
g.Wo)){O.channel_id=g.C(H.subscribeButton,g.Wo).channelId;H=g.C(H.subscribeButton,g.Wo);b=A=null;H.subscribed?(H.subscriberCountWithUnsubscribeText&&(A=g.Xn(H.subscriberCountWithUnsubscribeText)),H.subscriberCountText&&(b=g.Xn(H.subscriberCountText))):(H.subscriberCountText&&(A=g.Xn(H.subscriberCountText)),H.subscriberCountWithSubscribeText&&(b=g.Xn(H.subscriberCountWithSubscribeText)));let D=g.C(H.signInEndpoint?.commandMetadata,g.Xs)?.url||"";H={subscribeText:g.Xn(H.unsubscribedButtonText),subscribeCount:A||
"",unsubscribeText:g.Xn(H.subscribedButtonText),unsubscribeCount:b||"",enabled:H.enabled||!1,classic:!1,subscribed:H.subscribed||!1,feature:"iv",signInUrl:D};O.standalone_subscribe_button_data=H}k=new Vm5(r,"branding","branding",k,O);O=Nqq(K);K.player.O("web_player_overlay_positioned_layout")?(O.setAttribute("data-overlay-order","11"),K.player.Y7(O,4,!0)):K.Y.element.appendChild(O);k=new tmK(O,yp(K),k);k.Bn();g.W(k,k);K.W[r]=k}};
g.IB.prototype.mG=g.AH(41,function(K,H){var r=g.HP(this.mI());r&&r.mG(K,H)});var QF={},EN=null;g.lJ(xi,g.ZB);g.t=xi.prototype;g.t.getDuration=function(){return this.duration};
g.t.play=function(K){if(K||this.K==0)this.progress=0,this.coords=this.Y;else if(this.isPlaying())return!1;$i(this);this.startTime=K=g.St();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.N=this.startTime;this.progress||this.G8();this.Cf("play");this.isPaused()&&this.Cf("resume");this.K=1;var H=g.P5(this);H in QF||(QF[H]=this);lgL();WTL(this,K);return!0};
g.t.stop=function(K){$i(this);this.K=0;K&&(this.progress=1);G_Y(this,this.progress);this.onStop();this.r5()};
g.t.pause=function(){this.isPlaying()&&($i(this),this.K=-1,this.Cf("pause"))};
g.t.Vg=function(){this.K==0||this.stop(!1);this.Cf("destroy");xi.ti.Vg.call(this)};
g.t.destroy=function(){this.dispose()};
g.t.pV=function(){this.Cf("animate")};
g.t.Cf=function(K){this.dispatchEvent(new zgG(K,this))};
g.lJ(zgG,g.yG);g.lJ(P_,xi);P_.prototype.B=function(){};
P_.prototype.pV=function(){this.B();P_.ti.pV.call(this)};
P_.prototype.r5=function(){this.B();P_.ti.r5.call(this)};
P_.prototype.G8=function(){this.B();P_.ti.G8.call(this)};
g.lJ(g7,P_);g7.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var fax=class extends g.Le{constructor(K){super();this.Y=K||window;this.K=[]}listen(K,H,r,O){r=(0,g.g4)(r,O||this.Y);K=g.Dh(K,H,r);this.K.push(K);return K}JD(K,H,r,O){r=(0,g.g4)(r,O||this.Y);K=VeQ(K,H,r);this.K.push(K);return K}OE(K){g.yW(K);g.b0(this.K,K)}removeAll(){g.yW(this.K);this.K.length=0}Vg(){this.removeAll();super.Vg()}};var uvK=class extends g.R{constructor(K,H,r,O,A,k,b,D,y,B,Z){K=K.charAt(0)+K.substring(1).toLowerCase();r=r.charAt(0)+r.substring(1).toLowerCase();if(H==="0"||H==="-1")H=null;if(O==="0"||O==="-1")O=null;var F=Z.X(),X=F.userDisplayName&&g.c0(F);super({L:"div",ob:["ytp-button","ytp-sb"],J:[{L:"div",S:"ytp-sb-subscribe",U:X?{"data-tooltip-title":g.Tt("Subscribe as $USER_NAME",{USER_NAME:F.userDisplayName}),"aria-label":"Subscribe to channel","data-tooltip-image":g.Jr(F),"data-tooltip-opaque":String(g.Q8(F)),
tabindex:"0",role:"button"}:{"aria-label":"Subscribe to channel"},J:[{L:"div",S:"ytp-sb-text",J:[{L:"div",S:"ytp-sb-icon"},K]},H?{L:"div",S:"ytp-sb-count",ek:H}:""]},{L:"div",S:"ytp-sb-unsubscribe",U:X?{"data-tooltip-title":g.Tt("Subscribed as $USER_NAME",{USER_NAME:F.userDisplayName}),"aria-label":"Unsubscribe to channel","data-tooltip-image":g.Jr(F),"data-tooltip-opaque":String(g.Q8(F)),tabindex:"0",role:"button"}:{"aria-label":"Unsubscribe to channel"},J:[{L:"div",S:"ytp-sb-text",J:[{L:"div",S:"ytp-sb-icon"},
r]},O?{L:"div",S:"ytp-sb-count",ek:O}:""]}],U:{"aria-live":"polite"}});this.channelId=b;this.D=Z;var w=this.Rb("ytp-sb-subscribe"),T=this.Rb("ytp-sb-unsubscribe");k&&g.DB(this.element,"ytp-sb-classic");if(A){D?this.K():this.Y();var S=()=>{if(F.TF){var z=this.channelId;if(y||B){var m={c:z};var a;g.fX.isInitialized()&&(a=g.jt9(m));m=a||"";if(a=Z.getVideoData())if(a=a.subscribeCommand){var n=Z.iW();n?(g.RH(n,a,{botguardResponse:m,feature:y}),g.P6(Z,"SUBSCRIBE",z)):g.ts(Error("No innertube service available when updating subscriptions."))}else g.ts(Error("No subscribe command in videoData."));
else g.ts(Error("No video data available when updating subscription."))}T.focus();T.removeAttribute("aria-hidden");w.setAttribute("aria-hidden","true")}else g.LJ(g.go(this.D.X()),"sb_button",this.B)},G=()=>{var z=this.channelId;
if(y||B){var m=Z.getVideoData();g.RH(Z.iW(),m.unsubscribeCommand,{feature:y});g.P6(Z,"UNSUBSCRIBE",z)}w.focus();w.removeAttribute("aria-hidden");T.setAttribute("aria-hidden","true")};
this.Z(w,"click",S);this.Z(T,"click",G);this.Z(w,"keypress",z=>{z.keyCode===13&&S(z)});
this.Z(T,"keypress",z=>{z.keyCode===13&&G(z)});
this.Z(Z,"SUBSCRIBE",this.K);this.Z(Z,"UNSUBSCRIBE",this.Y)}else g.DB(w,"ytp-sb-disabled"),g.DB(T,"ytp-sb-disabled")}B(){window.location.reload()}K(){g.DB(this.element,"ytp-sb-subscribed")}Y(){g.j5(this.element,"ytp-sb-subscribed")}};var HSq=class extends g.We{constructor(K){super(K);this.N=this.endscreen=null;this.Y={};this.W={};this.V=this.B=null;this.j=[];this.K=null;this.Ib=!0;this.G=0;K=K.X();this.C=g.c0(K)||K.zF==="profilepage";this.events=new g.Zc(this);g.W(this,this.events);this.events.Z(this.player,g.e9("creatorendscreen"),this.onCueRangeEnter);this.events.Z(this.player,g.o8("creatorendscreen"),this.onCueRangeExit);this.events.Z(this.player,"resize",this.u1);this.events.Z(window,"focus",this.KK);this.load();var H=g.ka("STYLE");
(g.se("HEAD")[0]||document.body).appendChild(H);this.addOnDisposeCallback(()=>{g.Mu(H)});
H.sheet&&(H.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),H.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!UN(this)){var K=g.VkM(this.player.getVideoData());K?(K=Yi(K,mbK(this)),S4(this,K,!1)):hgS(this)}}unload(){S4(this,null);this.N&&(this.N.abort(),this.N=null);super.unload()}SH(K,H){return UN(this)?K==="loadCustomEndscreenRenderer"?(K=Yi(H,"new"),S4(this,K),!0):null:null}getOptions(){return UN(this)?["loadCustomEndscreenRenderer"]:[]}u1(){if(this.endscreen&&this.endscreen.elements){var K=this.player.getVideoContentRect();if(K&&K.width!==0&&K.height!==0){var H=this.player.getPlayerSize();
if(H&&H.width!==0&&H.height!==0){var r=K.width/K.height;var O=0;var A=-1;for(var k=0;k<py5.length;k++){var b=Math.abs(H.width-py5[k]);if(A===-1||O>=b)A=k,O=b}O=Rlx[A];this.B&&g.Ut(this.B.element,"outline-width",Math.max(H.width,H.height)+"px");for(H=0;H<this.endscreen.elements.length;++H){k=this.endscreen.elements[H].id;A=this.Y[k];b=this.W[k];if(!A||!b)continue;let y=b.width*r/b.aspectRatio;var D=Math.round(b.width*K.width);k=Math.round(y*K.height);let B=K.left+Math.round(b.left*K.width),Z=K.top+
Math.round(b.top*K.height);g.qu(A.element,D,k);g.C3(A.element,B,Z);g.Mq(A.element,izS);D>256||k>256?g.DB(A.element,"ytp-ce-large-round"):D>96||k>96?g.DB(A.element,"ytp-ce-medium-round"):g.DB(A.element,"ytp-ce-small-round");g.Mq(A.element,KUq);D=b.left+b.width/2;b=b.top+y/2;g.DB(A.element,D<=.5&&b<=.5?"ytp-ce-top-left-quad":D>.5&&b<=.5?"ytp-ce-top-right-quad":D<=.5&&b>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mq(A.element,Rlx);g.DB(A.element,O);(A=g.aw(document,"div","ytp-ce-expanding-overlay-body",
A.element)[0])&&g.Ut(A,"height",`${k}px`)}}}}}onCueRangeEnter(K){if(this.endscreen)if(K.getId()==="ytp-ce-in-endscreen")zs(this,this.endscreen.impressionUrls),(K=g.PZ())&&this.endscreen.visualElement&&g.DH(K,this.endscreen.visualElement),this.K&&(g.DB(this.K,"ytp-ce-element-show"),this.K.removeAttribute("aria-hidden"),this.player.uW()?g.DB(this.K,"ytp-ce-hide-button-lower"):g.j5(this.K,"ytp-ce-hide-button-lower"));else{K=K.getId().substring(15);var H=this.Y[K],r=this.W[K];g.DB(H.element,"ytp-ce-element-show");
H.element.removeAttribute("aria-hidden");H=this.player.getRootNode();g.DB(H,"ytp-ce-shown");zs(this,r.impressionUrls);(H=g.PZ())&&g.DH(H,r.visualElement);this.player.X().Ib&&g.P6(this.player,"endscreenelementshown",K)}}onCueRangeExit(K){if(K.getId()==="ytp-ce-in-endscreen")this.K&&(g.j5(this.K,"ytp-ce-element-show"),this.K.setAttribute("aria-hidden","true"));else{K=K.getId().substring(15);var H=this.Y[K];g.j5(H.element,"ytp-ce-element-show");H.element.setAttribute("aria-hidden","true");H=this.player.getRootNode();
g.j5(H,"ytp-ce-shown");this.player.X().Ib&&g.P6(this.player,"endscreenelementhidden",K)}}KK(K){K.target===window&&(new g.Ko(()=>{for(let H of Object.values(this.Y))g.Mq(H.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Au(K){for(let H of Object.values(this.Y))K?H.element.setAttribute("hidden",""):H.element.removeAttribute("hidden")}P4(K){this.K&&this.player.getRootNode().removeChild(this.K);
K&&(g.DB(K,"ytp-ce-hide-button-container"),this.K=K,g.hC(this.player,this.K,4))}},py5=[346,426,470,506,570,640,853,1280,1920],Rlx="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),KUq=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],izS=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var rOL=class{constructor(K,H,r,O){this.value=K;this.target=H;this.showLinkIcon=r;this.Y=O}K(){return this.value?this.value:null}},Hzx={At:"current",Jqn:"new"};var k84=class{constructor(K,H,r){this.type=K;this.trigger=H;this.url=r}},Ozx={CLOSE:"close",vYg:"openUrl",SUBSCRIBE:"subscribe"},AOK={mC:"click",CLOSE:"close",QE5:"hidden",aJ5:"rollOut",YMG:"rollOver",TYy:"shown"};var Vm5=class{constructor(K,H,r,O,A){this.id=K;this.type=H;this.style=r;this.data=A;this.action=O||[]}nB(){var K=Dh0(this,H=>H.type==="openUrl"&&H.url!=null);
return K?K.url:null}},SDS={Pr:"anchored",ou:"branding",CHANNEL:"channel",xO:"cta",Y1k:"highlightText",FIE:"label",PLAYLIST:"playlist",POPUP:"popup",kZg:"speech",SUBSCRIBE:"subscribe",cWg:"title",VIDEO:"video",m$0:"website"},UhB={ou:"branding",VI:"card",aE5:"drawer",auk:"highlight",TvG:"marker",MQ5:"promotion",TEXT:"text",EgF:"widget"};var rdY=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
OSQ=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var Ado=class{constructor(K,H){this.context=K;this.K=H}};var G8L=class{constructor(K,H){this.merchant=K;this.price=H}};var kiQ=class extends g.Le{constructor(K,H){super();this.element=K;this.context=H;this.fK=!1;this.ZE=new Map;this.Jy=new Map;this.context.D.addEventListener(g.e9("annotations_module"),r=>{(r=this.ZE.get(r))&&r.apply(this)});
this.context.D.addEventListener(g.o8("annotations_module"),r=>{(r=this.Jy.get(r))&&r.apply(this)})}addCueRange(K,H,r,O,A){K=new g.bZ(K,H,{id:r,
namespace:"annotations_module"});O&&this.ZE.set(K,O);A&&this.Jy.set(K,A);this.context.D.No([K],1)}Bn(){this.context.Y.subscribe("resize",this.iG,this)}zL(){return this.element}jk(K,H,r,O,A,k){if(this.fK)return!1;k&&(k.stopPropagation(),k.preventDefault());this.navigate(K,r,O,A);return!1}show(){}hide(){}destroy(){g.Mu(this.zL())}iG(){}navigate(K,H,r,O){var A=K.K();if(A){var k=Mmq(A,K.target),b=()=>{K.Y&&this.context.D.pauseVideo();var D=this.context.videoData.NQ||!1,y=g.zF(A||"");D&&y&&(y.v||y.list)?
this.context.D.v9(y.v,H,y.list,!1):g.yr(A||"",k==="current"?"_top":void 0,H)};
k==="new"&&(b(),b=null);Ds(this.context.logger,r,b,O);jl5(A)||(r=g.PZ(),O=H.itct,r&&O&&g.ME(r,g.QT(O)))}}Vg(){this.ZE.clear();this.Jy.clear();super.Vg()}createElement(K){K=new g.R(K);g.W(this,K);return K.element}};var uxq=class extends kiQ{constructor(K,H,r){super(H,r);this.D=K;this.eventId=null;this.V6=this.Pn=this.Wl=this.B=this.isInitialized=!1;this.cards=[];this.vn=this.j=this.wZ=this.V=this.hy=this.K=null;this.Ib=[];this.KK=this.G=this.Vb=this.TF=null;this.W=0;this.zF=new g.Ko(()=>{},r.Qg.QT?4E3:3E3);
g.W(this,this.zF);this.pK=new g.Ko(()=>{});
g.W(this,this.pK);this.Nd=new Ado(r,(O,A,k,b,D,y)=>{uQ(this,O,A,k,b,D,y)});
this.C=new g.R({L:"div",S:"iv-drawer",U:{id:"iv-drawer"},J:[{L:"div",S:"iv-drawer-header",U:{"aria-role":"heading"},J:[{L:"span",S:"iv-drawer-header-text"},{L:"button",ob:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{L:"div",S:"iv-drawer-content"}]});g.W(this,this.C);this.N=this.C.element;this.Ay=new g.t$(this.C,330);g.W(this,this.Ay);this.aE=g.he("iv-drawer-header-text",this.N);this.Y=g.he("iv-drawer-content",this.N);this.addCueRange(0,r.videoData.lengthSeconds*
1E3,"",()=>{this.Wl&&iQ(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.Wl=this.B)&&HJ(this)});
this.O5=new g.Zc(this);g.W(this,this.O5);this.D.addEventListener("videodatachange",this.qU.bind(this))}qU(){this.KK&&KK(this,this.KK)}isAvailable(){var K;if(K=!!this.cards.length)(K=this.D.getRootNode())?(K=g.p3(K),K=173<K.width&&173<K.height):K=!1;return K}iG(){var K=this.isAvailable();g.Rj(this.zL(),K);g.Bp(this.context.D.getRootNode(),g.km.IV_DRAWER_ENABLED,K);c_(this.D)}destroy(){this.D.mG(!1);try{this.D.getRootNode().removeChild(this.N)}catch(K){}g.MS(this.Ib);this.O5.Y();this.hy&&this.hy.dispose();
this.V&&this.V.dispose();super.destroy()}GP(){this.context.K.listen(g.he("iv-drawer-close-button",this.N),"click",this.kS,this);this.context.K.listen(this.Y,"touchend",()=>{this.zF.start()});
this.context.K.listen(this.Y,"scroll",this.CE,this);this.context.Y.subscribe("onHideControls",()=>{this.Pn=!0});
this.context.Y.subscribe("onShowControls",()=>{this.Pn=!1});
this.context.Y.subscribe("onVideoAreaChange",()=>{this.Pn=g.bd(this.D.getRootNode(),"ytp-autohide")});
this.Ib.push(g.jP("iv-button-shown",this.pE,this));this.Ib.push(g.jP("iv-button-hidden",this.d1,this));Zz4(this)}findLastIndex(K){if(this.cards.length===0)return 0;var H=g.K5(this.cards,r=>K.JW.startMs>r.JW.startMs||K.JW.startMs===r.JW.startMs&&K.JW.timestamp>=r.JW.timestamp?!0:!1);
return H===-1?0:H+1}kS(){if(this.B){Ds(this.context.logger,AX(this).Q0.close);var K=g.PZ();K&&this.G&&g.ME(K,this.G);HJ(this)}}CE(){g.Bp(this.N,"iv-drawer-scrolled",this.Y.scrollTop>0)}pE(){var K=g.PZ(),H=AX(this);H=H?H.Vb:this.Vb;K&&H&&g.yU(K,[H])}d1(){var K=g.PZ(),H=AX(this);H=H?H.Vb:this.Vb;K&&H&&g.jM(K,[H])}XH(){var K=AX(this);Ds(this.context.logger,K.Q0.mL);var H=g.PZ();if(H&&K){let r=[];K.d3&&r.push(K.d3);K.Vb&&r.push(K.Vb);r.length>0&&g.yU(H,r)}}E1(){var K=g.PZ(),H=AX(this);K&&H&&g.jM(K,[H.d3])}Pl(K){var H=
AX(this),r=g.PZ();this.K?K?(K=this.context.logger,Ds(K,H.Q0.LV),K.D.sendVideoStatsEngageEvent(4,void 0),r&&H.d3&&g.ME(r,H.d3)):(K=this.context.logger,Ds(K,H.Q0.LV),K.D.sendVideoStatsEngageEvent(4,void 0),r&&H.Vb&&g.ME(r,H.Vb)):(K=this.context.logger,Ds(K,H.Q0.LV),K.D.sendVideoStatsEngageEvent(4,void 0),r&&this.Vb&&g.ME(r,this.Vb))}};var bSS=class extends kiQ{constructor(K,H,r){super(K,H);this.annotation=r;this.isActive=!1}Bn(){super.Bn();QlQ(this)}show(){super.show();var K=g.PZ(),H=this.annotation.data;K&&H&&(H=H.session_data)&&g.yU(K,[g.QT(H.itct)])}hide(){super.hide();var K=g.PZ(),H=this.annotation.data;K&&H&&(H=H.session_data)&&g.jM(K,[g.QT(H.itct)])}};var tmK=class extends bSS{constructor(K,H,r){super(K,H,r);this.K=null;this.Y=!1}render(){g.DB(this.zL(),"iv-branding");var K=this.annotation.data;this.K=this.createElement({L:"img",ob:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:K.image_url,width:K.image_width,height:K.image_height}});g.Rj(this.K,!1);var H=this.createElement({L:"button",ob:["branding-img-container","ytp-button"]});H.appendChild(this.K);this.zL().appendChild(H);var r=this.annotation.nB();r&&uQ(this,H,
r,this.annotation.id,K.session_data)}show(){if(!this.isActive&&(super.show(),this.Y||(this.render(),this.Y=!0),g.Rj(this.zL(),!0),this.isActive=!0,this.K)){try{ELL(this,this.K)}catch{}g.DB(this.context.D.getRootNode(),"ytp-branding-shown");this.context.D.getRootNode().style.setProperty("--branding-image-width",`${this.K.getAttribute("width")}px`)}}hide(){this.isActive&&(super.hide(),g.Rj(this.zL(),!1),this.isActive=!1,g.j5(this.context.D.getRootNode(),"ytp-branding-shown"))}destroy(){g.j5(this.context.D.getRootNode(),
"ytp-branding-shown");super.destroy()}};var nLx=class{constructor(K,H,r,O,A,k,b){this.K=K;this.B=H;this.Qg=r;this.videoData=O;this.logger=A;this.D=k;this.Y=b}};var laS=class extends bSS{constructor(K,H,r){super(K,H,r);this.j=this.isCollapsed=this.C=!1;this.W=5E3;this.Y=this.B=this.K=this.N=null;this.G=this.createElement({L:"div",ob:["iv-promo-contents"]});this.V=new g.Ko(()=>{this.K.setAttribute("aria-hidden","true");g.Rj(this.B,!1);g.Rj(this.Y,!0)},700,this);
g.W(this,this.V)}render(){var K=this.annotation.data;if(this.annotation.style==="cta")var H=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")H=7;this.W=K.collapsedelay_ms||this.W;var r=["iv-promo","iv-promo-inactive"];this.zL().setAttribute("aria-hidden","true");this.zL().setAttribute("aria-label","Promotion");this.zL().tabIndex=0;var O=this.annotation.nB(),A=K.image_url;if(A){var k=this.createElement({L:"div",ob:["iv-promo-img","iv-click-target"]});A=this.createElement({L:"img",
U:{src:A,"aria-hidden":"true"}});k.appendChild(A);K.video_duration&&!K.is_live?(A=this.createElement({L:"span",S:"iv-promo-video-duration",ek:K.video_duration}),k.appendChild(A)):K.playlist_length&&(A=this.createElement({L:"span",S:"iv-promo-playlist-length",ek:K.playlist_length.toString()}),k.appendChild(A));O&&uQ(this,k,O,this.annotation.id,K.session_data,void 0,H)}O?(A=this.createElement({L:"a",S:"iv-promo-txt"}),g.zk(A,O.K()),this.K=A):this.K=this.createElement({L:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var b=
this.createElement({L:"p",J:[{L:"strong",ek:K.text_line_1}]});var D=this.createElement({L:"p",J:[{L:"span",S:"iv-promo-link",ek:K.text_line_2}]});if(A=K.text_line_3){r.push("iv-promo-website-card-cta-redesign");var y=this.createElement({L:"button",ob:["iv-promo-round-expand-icon","ytp-button"]});A=this.createElement({L:"button",ob:["iv-button","iv-promo-button"],J:[{L:"span",S:"iv-button-content",ek:A}]});var B=this.createElement({L:"div",S:"iv-promo-button-container"});B.appendChild(A);O&&uQ(this,
this.zL(),O,this.annotation.id,K.session_data,void 0,H)}g.DB(this.K,"iv-click-target");O&&uQ(this,this.K,O,this.annotation.id,K.session_data,void 0,H);break;case "playlist":case "video":b=this.createElement({L:"p",J:[{L:"span",ek:K.text_line_1}]}),D=this.createElement({L:"p",J:[{L:"strong",ek:K.text_line_2}]}),K.is_live&&(b=D,D=this.createElement({L:"span",ob:["yt-badge","iv-promo-badge-live"],ek:"LIVE NOW"})),g.DB(this.K,"iv-click-target"),O&&uQ(this,this.K,O,this.annotation.id,K.session_data,void 0,
H),r.push("iv-promo-video")}b&&this.K.appendChild(b);D&&this.K.appendChild(D);this.G.appendChild(this.K);B&&this.G.appendChild(B);H=this.createElement({L:"div",S:"iv-promo-actions"});this.Y=this.createElement({L:"button",ob:["iv-promo-expand","ytp-button"]});this.Y.title="Expand";this.context.K.listen(this.Y,"click",Z=>{kZ(this,5E3,Z)});
H.appendChild(this.Y);g.Rj(this.Y,!1);this.context.K.listen(this.zL(),"mouseover",this.zF,this);this.context.K.listen(this.zL(),"mouseout",this.Nd,this);this.context.K.listen(this.zL(),"touchend",Z=>{kZ(this,5E3,Z)});
this.B=this.createElement({L:"button",ob:["iv-promo-close","ytp-button"]});this.B.title="Close";this.context.K.listen(this.B,"click",this.annotation.style==="cta"&&K.text_line_3?this.KK:this.Ib,this);H.appendChild(this.B);g.y0(this.zL(),r);k&&(g.DC(this.zL(),k),y&&k.appendChild(y));g.DC(this.zL(),this.G);g.DC(this.zL(),H)}show(){this.isActive||(super.show(),this.C||(this.render(),this.C=!0),g.Rj(this.zL(),!0),g.Cz(function(){g.j5(this.zL(),"iv-promo-inactive")},100,this),this.zL().removeAttribute("aria-hidden"),
this.isActive=!0,bk(this),$hL(this),xhL(this,this.W))}hide(){this.isActive&&(g.DB(this.zL(),"iv-promo-inactive"),this.isActive=!1,this.zL().setAttribute("aria-hidden","true"))}jk(K,H,r,O,A,k){return this.isCollapsed?!1:super.jk(K,H,r,O,A,k)}zF(K){this.j=!0;
kZ(this,500,K)}Nd(){this.j=!1;Piu(this)}Ib(K){K.stopPropagation();this.hide()}KK(K){K.stopPropagation();bk(this);this.isCollapsed=!0;g.DB(this.zL(),"iv-promo-collapsed-no-delay");this.V.start()}destroy(){this.V.dispose();super.destroy()}};var Dmq=class{constructor(K){this.D=K}};g.u4("annotations_module",class extends g.We{constructor(K){super(K);this.Ib=this.KK=!1;this.loadNumber=0;this.W={};this.logger=new Dmq(this.player);this.V=new g.Zc(this);this.G=this.N=null;this.events=new g.Zc(this);this.hI=this.j=this.K=null;this.Bn=[];g.W(this,this.V);this.V.Z(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.V.Z(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.V.Z(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.V.Z(this.player,"resize",r=>{this.publish("resize",r)});
this.V.Z(this.player,"presentingplayerstatechange",r=>{this.publish("presentingplayerstatechange",r)});
this.subscribe("presentingplayerstatechange",this.zF,this);this.subscribe("resize",this.C,this);this.player.X().O5.subscribe("vast_info_card_add",this.Nd,this);g.W(this,this.events);this.iG=this.createElement({L:"div",S:"video-custom-annotations"});this.Y=new g.R({L:"div",ob:["ytp-player-content","ytp-iv-player-content"]});g.W(this,this.Y);g.hC(this.player,this.Y.element,4);this.Y.hide();this.B=new g.R({L:"div",ob:["ytp-iv-video-content"]});g.W(this,this.B);K=this.createElement({L:"div",S:"video-annotations"});
K.appendChild(this.iG);this.B.element.appendChild(K);this.Df()?this.load():this.player.O("web_fix_annotations")&&(this.N=()=>{this.loaded||this.Md()||!this.Df()||(Lqq(this),this.load())},this.player.addEventListener("videodatachange",this.N));
var H=this.createElement({L:"style"});(g.se("HEAD")[0]||document.body).appendChild(H);this.addOnDisposeCallback(()=>{g.Mu(H)});
if(K=H.sheet){for(let r of rdY)K.insertRule(r,0);for(let r of OSQ)K.insertRule(r,0)}}SH(K,H){if(!gL4(this.player.X().playerStyle))return null;switch(K){case "loadCustomAnnotationsXml":return(K=g.C8(H))&&jQ(this,K),!0;case "removeCustomAnnotationById":return H&&this.K&&(pT(this.K,H),c_(this.player)),!0}return null}getOptions(){return gL4(this.player.X().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Df(){var K=this.player.getVideoData(),H=K.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return K.NQ||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.O("web_fix_annotations")?zlY(this)?H?.isWatermarkEnforced===!0?!0:H?.isAnnotationsEnabled??!1:!1:zlY(this)}C(){if(this.B){var K=this.player.uG().getVideoContentRect(!0);g.qu(this.B.element,K.width,K.height);g.C3(this.B.element,K.left,K.top)}if(this.K){var H=this.player.EO();K=this.K;H=H.width;g.Bp(K.N,"iv-drawer-small",H<=426);g.Bp(K.N,"iv-drawer-big",H>=1280)}}zF(K){CiL(this,K.state);K.state.K(2)&&(this.uW()&&this.LM()&&this.player.getPresentingPlayerType()!==
2&&this.Hg(!1),this.mG(!1))}load(){super.load();CiL(this,this.player.getPlayerStateObject());this.loadNumber++;var K=this.player.getVideoData();aa0(this,K);g.hC(this.player,this.B.element,4);this.C();var H=g.jX(K),r=g.yv(K);if(this.player.O("web_fix_annotations")){if(H&&(H.featuredChannel&&qDS(this,H.featuredChannel,H.annotationId||"branding",K.videoId||null,K.eventId||null),H=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,H?.isWatermarkEnforced&&!H?.isAnnotationsEnabled))return;
r&&MO(this,r)}else r&&MO(this,r),H&&H.featuredChannel&&qDS(this,H.featuredChannel,H.annotationId||"branding",K.videoId||null,K.eventId||null);this.hI=g.he("ytp-cards-button",this.player.getRootNode());g.De(K)&&mhQ(this,K)}onVideoDataChange(){}unload(){this.player.sN("annotations_module");for(let K of Object.keys(this.W))this.W[K].destroy();this.j=null;this.K&&(this.K.destroy(),this.K=null,c_(this.player));this.KK=!1;this.G&&(this.G.abort(),this.G=null);this.Ib=!1;this.W={};this.Y.hide();super.unload();
this.B.detach();Lqq(this)}Nd(K){K===this.player.getVideoData().videoId&&(this.loaded?hlx(this):this.load())}uW(){return this.K?.isAvailable()||this.Ib}LM(){return!!this.K&&this.K.B}Hg(K,H=!1,r){this.uW();this.K&&(K?r?iQ(this.K,r,H):iQ(this.K,"YOUTUBE_DRAWER_AUTO_OPEN",H):HJ(this.K))}mG(K,H){this.player.publish(K?"cardsteasershow":"cardsteaserhide",H)}Vg(){this.player.X().O5.unsubscribe("vast_info_card_add",this.Nd,this);g.j5(this.player.getRootNode(),g.km.IV_DRAWER_OPEN);var K=this.Bn,H=g.sL;for(let r=
0,O=K.length;r<O;r++)H.BU(K[r]);this.Bn.length=0;super.Vg()}createElement(K){K=new g.R(K);g.W(this,K);return K.element}});g.u4("creatorendscreen",HSq);})(_yt_player);
