<?xml version="1.0"?>
<package format="2">
  <name>urdf_humanoid</name>
  <version>0.1.0</version>
  <description>Ready-to-use humanoid URDFs in Gazebo Classic for force/joint experiments.</description>
  <maintainer email="ben@example.com">ben</maintainer>
  <license>BSD</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
</package>
