/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ifadapter -a ifadapter.h:ifadapter.cpp com.dbus.example.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ifadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ifadapter
 */

ifadapter::ifadapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ifadapter::~ifadapter()
{
    // destructor
}

QString ifadapter::sendCommand(const QString &aCommand)
{
    // handle method call ben.interfacedescription.sendCommand
    QString out0;
    QMetaObject::invokeMethod(parent(), "sendCommand", Q_RETURN_ARG(QString, out0), Q_ARG(QString, aCommand));
    return out0;
}

